### ISSUE TITLE
Configurable Publishers  / Consumers

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-rabbitmq#4]
## Rationale 
Working with channels, queues and exchanges directly can be overwhelming. The same API is used for multiple RabbitMQ topologies, and the code has a bunch of confusing code arguments. Let's create configurable RabbitMQ "producers" and "subscriptions" that encapsulate a topology, and provide a simple API for sending or receiving messages.

## Config Format

```yaml
rabbitmq:
  connections:
    c1: {}
  exchanges:
    e1: {}
  queues:
    q1: {}

  # New - publish and subscribe "endpoints"
  pub:
    p1:
      connection: c1
      exchange: e1
      routingKey: k1

  sub:
    s1:
      connection: c1
      queue: q1 # read from a named queue not bound to an exchange (e.g. multiple workers scenario)
    s2:
      connection: c1
      exchange: e1 # read from the exchange (per-consumer queue is created implicitly)
    s3:
      connection: c1
      exchange: e1
      queue: q1 # read from a named queue bound to the exchange (e.g. multiple workers scenario)
      autoAck: true # more parameters...
```
Referencing undeclared queues should work. Those will be crated with default configuration. Referencing undeclared exchanges will not work, as we need to know the exchange type (e.g. TOPIC) to be able to create an exchange.

##  Java API

The API would revolve around a concept of "pub" or "sub" _endpoint_. Endpoint is a Bootique abstraction not present in RMQ that would allow us to simplify access to a specific preconfigured topology. An injectable `RmqEndpoints` would provide access to endpoints:

```java
@Inject
RmqEndpoints endpoints;

endpoints.pub("p0").publish("M1".getBytes())

endpoints.pub("p1")
        .newMessage()
	.routingKey("alt-routing")
	.publish("M2".getBytes())

endpoints.sub("s1")
	.newSubscription()
        .queue("q1")
        .subscribe(consumer);
```

### Channel pooling

see #9

### Message (de)serializers

An improvement for producer / consumer would be adding automated conversion between binary and object representation of messages. Once we implement the scope above, we can add (de)serializers and even make Producer/Consumer parameterized on supported message type.
